"""add skins catalog and user inventory

Revision ID: 07e6fa35699e
Revises: 4c1982dbff78
Create Date: 2026-02-20 15:28:46.991090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e6fa35699e'
down_revision = '4c1982dbff78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(length=32), nullable=False),
    sa.Column('weapon', sa.String(length=64), nullable=False),
    sa.Column('skin_name', sa.String(length=128), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=False),
    sa.Column('collection', sa.String(length=128), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_skins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('catalog_skin_id', sa.Integer(), nullable=False),
    sa.Column('wear', sa.String(length=32), nullable=True),
    sa.Column('stattrak', sa.Boolean(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('buy_price_eur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_skin_id'], ['skins_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_skins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skins_catalog_skin_id'), ['catalog_skin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_skins_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skins_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_skins_catalog_skin_id'))

    op.drop_table('user_skins')
    op.drop_table('skins_catalog')
    # ### end Alembic commands ###
