SHELL := /bin/bash

.PHONY: cluster-up cluster-down platform-bootstrap app-deploy verify

cluster-up:
	@./scripts/cluster-up.sh

cluster-down:
	@./scripts/cluster-down.sh

platform-bootstrap:
	@./scripts/platform-bootstrap.sh

app-deploy:
	@./scripts/app-deploy.sh

verify:
	@./scripts/verify.sh
